import 'package:equatable/equatable.dart';
import 'package:uuid/uuid.dart';

/// Type of collection
enum CollectionType {
  /// Auto-managed favorites collection
  favorites,

  /// User-created custom collection
  custom,

  /// System-generated collections (e.g., "Energetic Days", "Calm Moments")
  auto,
}

/// Collection - Organizes artworks into themed groups
/// Can be favorites, user-created, or auto-generated by the system
class Collection extends Equatable {
  /// Unique identifier for this collection
  final String id;

  /// Name of the collection
  final String name;

  /// Optional description
  final String? description;

  /// Type of collection (favorites, custom, auto)
  final CollectionType type;

  /// List of artwork IDs in this collection
  final List<String> artworkIds;

  /// Artwork ID to use as collection cover
  final String? coverArtworkId;

  /// SF Symbol icon name for this collection
  final String? iconName;

  /// Theme color for this collection (hex string)
  final String? colorHex;

  /// Timestamp when collection was created
  final DateTime createdAt;

  /// Timestamp when collection was last updated
  final DateTime updatedAt;

  // ============================================================================
  // CONSTRUCTORS
  // ============================================================================

  /// Main constructor
  const Collection({
    required this.id,
    required this.name,
    required this.type,
    required this.artworkIds,
    required this.createdAt,
    required this.updatedAt,
    this.description,
    this.coverArtworkId,
    this.iconName,
    this.colorHex,
  });

  /// Create a new collection with auto-generated ID and timestamps
  factory Collection.create({
    required String name,
    required CollectionType type,
    String? description,
    List<String>? artworkIds,
    String? coverArtworkId,
    String? iconName,
    String? colorHex,
  }) {
    final now = DateTime.now();
    return Collection(
      id: const Uuid().v4(),
      name: name,
      type: type,
      description: description,
      artworkIds: artworkIds ?? [],
      coverArtworkId: coverArtworkId,
      iconName: iconName,
      colorHex: colorHex,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Create a collection from a database map
  factory Collection.fromMap(Map<String, dynamic> map) {
    return Collection(
      id: map['id'] as String,
      name: map['name'] as String,
      description: map['description'] as String?,
      type: CollectionType.values.firstWhere(
        (e) => e.name == map['type'] as String,
      ),
      artworkIds: map['artworkIds'] != null
          ? (map['artworkIds'] as String).split(',').where((s) => s.isNotEmpty).toList()
          : [],
      coverArtworkId: map['coverArtworkId'] as String?,
      iconName: map['iconName'] as String?,
      colorHex: map['colorHex'] as String?,
      createdAt: DateTime.parse(map['createdAt'] as String),
      updatedAt: DateTime.parse(map['updatedAt'] as String),
    );
  }

  // ============================================================================
  // METHODS
  // ============================================================================

  /// Convert collection to database map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'type': type.name,
      'artworkIds': artworkIds.join(','),
      'coverArtworkId': coverArtworkId,
      'iconName': iconName,
      'colorHex': colorHex,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  /// Create a copy of this collection with updated fields
  /// Automatically updates the updatedAt timestamp
  Collection copyWith({
    String? id,
    String? name,
    String? description,
    CollectionType? type,
    List<String>? artworkIds,
    String? coverArtworkId,
    String? iconName,
    String? colorHex,
    DateTime? createdAt,
  }) {
    return Collection(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      type: type ?? this.type,
      artworkIds: artworkIds ?? this.artworkIds,
      coverArtworkId: coverArtworkId ?? this.coverArtworkId,
      iconName: iconName ?? this.iconName,
      colorHex: colorHex ?? this.colorHex,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: DateTime.now(),
    );
  }

  /// Add an artwork to this collection
  /// Returns a new Collection with the artwork added
  Collection addArtwork(String artworkId) {
    if (artworkIds.contains(artworkId)) {
      return this;
    }
    return copyWith(
      artworkIds: [...artworkIds, artworkId],
    );
  }

  /// Remove an artwork from this collection
  /// Returns a new Collection with the artwork removed
  Collection removeArtwork(String artworkId) {
    return copyWith(
      artworkIds: artworkIds.where((id) => id != artworkId).toList(),
    );
  }

  // ============================================================================
  // GETTERS
  // ============================================================================

  /// Returns the number of artworks in this collection
  int get artworkCount => artworkIds.length;

  /// Returns true if this collection has no artworks
  bool get isEmpty => artworkIds.isEmpty;

  // ============================================================================
  // EQUATABLE
  // ============================================================================

  @override
  List<Object?> get props => [
        id,
        name,
        description,
        type,
        artworkIds,
        coverArtworkId,
        iconName,
        colorHex,
        createdAt,
        updatedAt,
      ];
}
